# Generated by Django 4.2.15 on 2025-05-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('broker_id', models.AutoField(primary_key=True, serialize=False)),
                ('broker_name', models.CharField(max_length=255)),
                ('broker_logo', models.ImageField(blank=True, null=True, upload_to='broker_logos/')),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('min_account_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('account_opening_link', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Broker',
                'verbose_name_plural': 'Brokers',
                'ordering': ['broker_name'],
            },
        ),
    ]
