# Generated by Django 4.2.15 on 2025-05-30 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('ipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_band', models.CharField(blank=True, max_length=50, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('issue_size', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Open', 'Open'), ('Closed', 'Closed'), ('Listed', 'Listed')], default='Upcoming', max_length=10)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(1000)])),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(1000)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipos', to='ipo_app.company')),
            ],
            options={
                'verbose_name': 'IPO',
                'verbose_name_plural': 'IPOs',
                'ordering': ['-open_date'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='ipo_documents/rhp/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='ipo_documents/drhp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ipo_app.ipo')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
